# Convert binary file to C++ header with byte array
# Usage: cmake -DINPUT_FILE=shader.cso -DOUTPUT_FILE=shader.h -DARRAY_NAME=shader_data -P bin2header.cmake

if(NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT ARRAY_NAME)
    message(FATAL_ERROR "Usage: cmake -DINPUT_FILE=<file> -DOUTPUT_FILE=<file> -DARRAY_NAME=<name> -P bin2header.cmake")
endif()

# Read binary file
file(READ ${INPUT_FILE} BINARY_DATA HEX)

# Get file size
file(SIZE ${INPUT_FILE} FILE_SIZE)

# Convert hex string to byte array format
string(LENGTH "${BINARY_DATA}" HEX_LENGTH)
set(BYTE_ARRAY "")
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")

set(LINE_LENGTH 0)
foreach(i RANGE 0 ${BYTE_COUNT})
    math(EXPR POS "${i} * 2")
    string(SUBSTRING "${BINARY_DATA}" ${POS} 2 BYTE)
    
    if(BYTE)
        if(LINE_LENGTH EQUAL 0)
            set(BYTE_ARRAY "${BYTE_ARRAY}    ")
        endif()
        
        set(BYTE_ARRAY "${BYTE_ARRAY}0x${BYTE}, ")
        math(EXPR LINE_LENGTH "${LINE_LENGTH} + 1")
        
        if(LINE_LENGTH EQUAL 16)
            set(BYTE_ARRAY "${BYTE_ARRAY}\n")
            set(LINE_LENGTH 0)
        endif()
    endif()
endforeach()

# Remove trailing comma and space
string(REGEX REPLACE ", \n$" "\n" BYTE_ARRAY "${BYTE_ARRAY}")
string(REGEX REPLACE ", $" "" BYTE_ARRAY "${BYTE_ARRAY}")

# Generate header file
file(WRITE ${OUTPUT_FILE} 
"// Auto-generated from ${INPUT_FILE}
// DO NOT EDIT - Generated by cmake/bin2header.cmake

#pragma once
#include <cstdint>
#include <cstddef>

namespace ShaderBytecode {

static const uint8_t ${ARRAY_NAME}[] = {
${BYTE_ARRAY}
};

static const size_t ${ARRAY_NAME}_size = ${FILE_SIZE};

} // namespace ShaderBytecode
")

message(STATUS "Generated ${OUTPUT_FILE} (${FILE_SIZE} bytes)")
